# Generated by Django 5.0.4 on 2024-04-07 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
